version: '3'
services:
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - ./data:/data
    node:
        image: node:latest
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        volumes:
            - ./:/home/node/app
        ports:
            - 8000:8000
        command: npm run dev
    postgres:
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: mypass
        volumes:
            - ./pgdata:/var/lib/postgresql/data